apiVersion: v1
kind: Service
metadata:
  name: recipes-service
  labels:
    app: recipes-service
    app.kubernetes.io/name: recipes-service
    app.kubernetes.io/part-of: munchora
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: recipes-service
    component: server
