# Use the Node.js base image
FROM node:20-alpine AS development-env

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependency installation
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Start the application in development mode
CMD ["npm", "run", "dev"]