apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: munchora
data:
  NODE_ENV: 'production'
  VITE_ENV: 'development'
  # External API URL (accessed from browser)
  VITE_BASE_URL: 'http://munchora.local/api/v1'
  # Internal API URL (accessed from SSR server)
  VITE_BASE_URL_SSR: 'http://nginx-service/api/v1'
