apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: local-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: munchora
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/websocket-services: "notifications-service"
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 3000

          - path: /recipes
            pathType: Prefix
            backend:
              service:
                name: recipes-service
                port:
                  number: 3000

          - path: /shopping-lists
            pathType: Prefix
            backend:
              service:
                name: shopping-lists-service
                port:
                  number: 3000

          - path: /ai
            pathType: Prefix
            backend:
              service:
                name: ai-service
                port:
                  number: 3000

          - path: /notifications
            pathType: Prefix
            backend:
              service:
                name: notifications-service
                port:
                  number: 3000