apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-lists-service-config
  labels:
    app.kubernetes.io/name: shopping-lists-service
    app.kubernetes.io/part-of: munchora
data:
  RAILS_RELATIVE_URL_ROOT: '/shopping-lists'
  DB_HOST: 'shopping-lists-mysql-service'
  MYSQL_PORT: '3306'
  MYSQL_USER: 'munchora'
