apiVersion: v1
kind: Service
metadata:
  name: auth-mysql-service
  labels:
    app: auth-mysql
    app.kubernetes.io/name: auth-mysql
    app.kubernetes.io/part-of: munchora
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: auth-mysql
