apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: munchora
data:
  RAILS_RELATIVE_URL_ROOT: '/auth'
  DB_HOST: 'auth-mysql-service'
  MYSQL_PORT: '3306'
  MYSQL_USER: 'munchora'
