services:
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - recipes
      - shopping-lists
      - ai
    networks:
      - app-network

  ai:
    build:
      context: ./backend/ai-service
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    env_file:
      - ./backend/ai-service/.env.dev
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /ai
    volumes:
      - ./backend/ai-service:/app
      - ai-bundle:/usr/local/bundle # Ensure that Gems aren't installed on each build
    depends_on:
      - ai-db
    networks:
      - app-network

  ai-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ai_development
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: munchora
      MYSQL_PASSWORD: admin
#      MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS: 1
#    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    volumes:
      - ai-db-data:/var/lib/mysql
    networks:
      - app-network

  auth:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    env_file:
      - ./backend/auth-service/.env.dev
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /auth
    volumes:
      - ./backend/auth-service:/app
      - auth-bundle:/usr/local/bundle
    depends_on:
      - auth-db
    networks:
      - app-network

  auth-db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: auth_development
      MYSQL_USER: munchora
      MYSQL_PASSWORD: admin
      MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS: 1
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    volumes:
      - auth-db-data:/var/lib/mysql
    networks:
      - app-network

  recipes:
    build:
      context: ./backend/recipes-service
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    env_file:
      - ./backend/recipes-service/.env.dev
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /recipes
    volumes:
      - ./backend/recipes-service:/app
      - recipes-bundle:/usr/local/bundle
    depends_on:
      - recipes-db
    networks:
      - app-network

  recipes-db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: recipes_development
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: munchora
      MYSQL_PASSWORD: admin
      MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS: 1
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    volumes:
      - recipes-db-data:/var/lib/mysql
    networks:
      - app-network

  shopping-lists:
    build:
      context: ./backend/shopping-lists-service
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    env_file:
      - ./backend/shopping-lists-service/.env.dev
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /shopping-lists
    volumes:
      - ./backend/shopping-lists-service:/app
      - shopping-lists-bundle:/usr/local/bundle
    depends_on:
      - shopping-lists-db
    networks:
      - app-network

  shopping-lists-db:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: shopping_lists_development
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: munchora
      MYSQL_PASSWORD: admin
      MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS: 1
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    volumes:
      - shopping-lists-db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  auth-db-data:
  recipes-db-data:
  shopping-lists-db-data:
  ai-db-data:
  ai-bundle:
  auth-bundle:
  recipes-bundle:
  shopping-lists-bundle:


networks:
  app-network:
    driver: bridge