# ===========================================================================================================
#                            🐳 🐳 🐳 🐳 🐳 DOCKER COMPOSE DEV 🐳 🐳 🐳 🐳 🐳
# ===========================================================================================================
# docker-compose up:    docker-compose -f docker-compose.dev.yml up
# docker-compose logs:  docker-compose -f docker-compose.dev.yml logs -f
# docker-compose down:  docker-compose -f docker-compose.dev.yml down --rmi all --remove-orphans
#                       // Deletes all images - JUST MAKE SURE VOLUMES WON'T BE DELETED
#
# Generate a mysql dump file: docker exec -i <servie-name> mysqldump -u root -padmin <db_name> > ./munchora_dump.sql
# Interact with running docker based mysql: docker exec -it <containerID / name> mysql -u root -padmin
# Interact with docker based rails app: docker-compose exec <docker name> bash
# IF NEW GEM ADDED BUILD THE APP AGAIN: docker-compose -f docker-compose.dev.yml build <compose name - e.g. auth>
# ADD MIGRATIONS: docker-compose exec <docker name> bundle exec rails db:migrate
# Trigger hotreload by reloading service: docker-compose -f docker-compose.dev.yml restart recipes-rabbitmq-consumer

services:
  # ==============================
  # NGINX
  # ==============================
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - recipes
      - shopping-lists
      - ai
    networks:
      - app-network


  # ==============================
  # MYSQL
  # ==============================
  munchora-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: munchora
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
      - munchora-db-data:/var/lib/mysql
    networks:
      - app-network

  # ==============================
  # RABBITMQ
  # ==============================
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672" # GUI and management PORT
      # - "15692:15692" # Port for exposing metrics to Prometheus
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - app-network
    command: rabbitmq-server -rabbitmq_management listener [{port,15672}] -rabbitmq_prometheus [{port,15692}]
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # ==============================
  # Frontend RRv7 APP
  # ==============================
  frontend-app:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network

  # ==============================
  # AI DOMAIN
  # ==============================
  x-ai-service: &ai-service
    image: ai-service:dev
    env_file:
      - ./backend/ai-service/.env.dev
    volumes:
      - ./backend/ai-service:/app
    networks:
      - app-network

  ai-build:
    image: ai-service:dev
    build:
      context: ./backend/ai-service
      dockerfile: Dockerfile.dev

  ai:
    <<: *ai-service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /ai
    depends_on:
      munchora-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  ai-rabbitmq-consumer:
    <<: *ai-service
    command: bundle exec ruby bin/rabbitmq_consumer_runner.rb
    environment:
      RAILS_ENV: development
    depends_on:
      munchora-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  ai-sidekiq:
    <<: *ai-service
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      RAILS_ENV: development
    depends_on:
      munchora-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  # ==============================
  # AUTH DOMAIN
  # ==============================
  auth:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    env_file:
      - ./backend/auth-service/.env.dev
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /auth
    volumes:
      - ./backend/auth-service:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      munchora-db:
        condition: service_started
    networks:
      - app-network

  # ==============================
  # NOTIFICATIONS DOMAIN
  # ==============================
  x-notifications-service: &notifications-service
    image: notifications-service:dev
    env_file:
      - ./backend/notifications-service/.env.dev
    volumes:
      - ./backend/notifications-service:/app
    networks:
      - app-network

  notifications-build:
    image: notifications-service:dev
    build:
      context: ./backend/notifications-service
      dockerfile: Dockerfile.dev

  notifications:
    <<: *notifications-service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /notifications
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  notifications-rabbitmq-consumer:
    <<: *notifications-service
    command: bundle exec ruby lib/rabbitmq_consumer_runner.rb
    environment:
      RAILS_ENV: development
    depends_on:
      munchora-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  # ==============================
  # RECIPES DOMAIN
  # ==============================
  x-recipes-service: &recipes-service
    image: recipes-service:dev
    env_file:
      - ./backend/recipes-service/.env.dev
    volumes:
      - ./backend/recipes-service:/app
    networks:
      - app-network

  recipes-build:
    image: recipes-service:dev
    build:
      context: ./backend/recipes-service
      dockerfile: Dockerfile.dev

  recipes:
    <<: *recipes-service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /recipes
    volumes:
      - ./backend/recipes-service:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      munchora-db:
        condition: service_started

  recipes-rabbitmq-consumer:
    <<: *recipes-service
    command: bundle exec rails runner lib/rabbitmq_consumer_runner.rb
    environment:
      RAILS_ENV: development
    depends_on:
      munchora-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  # ==============================
  # SHOPPING_LISTS DOMAIN
  # ==============================
  x-shopping-lists-service: &shopping-lists-service
    image: shopping-lists-service:dev
    env_file:
      - ./backend/shopping-lists-service/.env.dev
    volumes:
      - ./backend/shopping-lists-service:/app
    networks:
      - app-network

  shopping-lists-build:
    image: shopping-lists-service:dev
    build:
      context: ./backend/shopping-lists-service
      dockerfile: Dockerfile.dev

  shopping-lists:
    <<: *shopping-lists-service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /shopping-lists
    depends_on:
      rabbitmq:
        condition: service_healthy
      munchora-db:
        condition: service_started

volumes:
  munchora-db-data:
  rabbitmq_data: # Stores RabbitMQ data
  rabbitmq_log: # Stores RabbitMQ logs


networks:
  app-network:
    driver: bridge