# ===========================================================================================================
#                            🐳 🐳 🐳 🐳 🐳 DOCKER COMPOSE DEV 🐳 🐳 🐳 🐳 🐳
# ===========================================================================================================
# docker-compose up:    docker-compose -f docker-compose.dev.yml up
# docker-compose logs:  docker-compose -f docker-compose.dev.yml logs -f
# docker-compose down:  docker-compose -f docker-compose.dev.yml down --rmi all --remove-orphans
#                       // Deletes all images - JUST MAKE SURE VOLUMES WON'T BE DELETED
#
# Generate a mysql dump file: docker exec -i <servie-name> mysqldump -u root -padmin <db_name> > ./munchora_dump.sql
# Interact with running docker based mysql: docker exec -it <containerID / name> mysql -u root -padmin
# Interact with docker based rails app: docker-compose exec <docker name> bash
# IF NEW GEM ADDED BUILD THE APP AGAIN: docker-compose -f docker-compose.dev.yml build <compose name - e.g. auth>
# ADD MIGRATIONS: docker-compose exec <docker name> bundle exec rails db:migrate
# Trigger hotreload by reloading service: docker-compose -f docker-compose.dev.yml restart recipes-rabbitmq-consumer

services:
  # ==============================
  # MYSQL
  # ==============================
  munchora-test-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: munchora
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql-init-test.sql:/docker-entrypoint-initdb.d/init.sql
      - munchora-test-db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  munchora-test-db-data:

networks:
  app-network:
    driver: bridge