# ===========================================================================================================
#                            🐳 🐳 🐳 🐳 🐳 DOCKER COMPOSE DEV 🐳 🐳 🐳 🐳 🐳
# ===========================================================================================================
# docker-compose up:    docker-compose -f docker-compose.dev.yml up
# docker-compose logs:  docker-compose -f docker-compose.dev.yml logs -f
# docker-compose down:  docker-compose -f docker-compose.dev.yml down --rmi all --remove-orphans
#                       // Deletes all images - JUST MAKE SURE VOLUMES WON'T BE DELETED
#
# Generate a mysql dump file: docker exec -i <servie-name> mysqldump -u root -padmin <db_name> > ./munchora_dump.sql
# Interact with running docker based mysql: docker exec -it <containerID / name> mysql -u root -padmin
# Interact with docker based rails app: docker-compose exec <docker name> bash
# IF NEW GEM ADDED BUILD THE APP AGAIN: docker-compose -f docker-compose.dev.yml build <compose name - e.g. auth>
# ADD MIGRATIONS: docker-compose exec <docker name> bundle exec rails db:migrate

services:
  # ==============================
  # NGINX
  # ==============================
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - recipes
      - shopping-lists
      - ai
    networks:
      - app-network

  # ==============================
  # RABBITMQ
  # ==============================
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672" # GUI and management PORT
      # - "15692:15692" # Port for exposing metrics to Prometheus
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - app-network
    command: rabbitmq-server -rabbitmq_management listener [{port,15672}] -rabbitmq_prometheus [{port,15692}]
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # ==============================
  # Frontend RRv7 APP
  # ==============================
  frontend-app:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network

  ai:
    build:
      context: ./backend/ai-service
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    env_file:
      - ./backend/ai-service/.env.dev
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /ai
    volumes:
      - ./backend/ai-service:/app
    depends_on:
      ai-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  ai-sidekiq:
    build:
      context: ./backend/ai-service
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file:
      - ./backend/ai-service/.env.dev
    environment:
      RAILS_ENV: development
    volumes:
      - ./backend/ai-service:/app
    depends_on:
      ai-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

#  ai-rabbitmq-consumer:
#    build:
#      context: ./backend/ai-service
#      dockerfile: Dockerfile.dev
#    command: bundle exec ruby lib/rabbitmq_consumer.rb
#    depends_on:
#      ai-db:
#        condition: service_started
#      rabbitmq:
#        condition: service_healthy

  ai-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ai_development
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: munchora
      MYSQL_PASSWORD: admin
    #      MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS: 1
    #    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    volumes:
      - ai-db-data:/var/lib/mysql
    networks:
      - app-network

  auth:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    env_file:
      - ./backend/auth-service/.env.dev
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /auth
    volumes:
      - ./backend/auth-service:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      auth-db:
        condition: service_started
    networks:
      - app-network

  auth-db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: auth_development
      MYSQL_USER: munchora
      MYSQL_PASSWORD: admin
    #      MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS: 1
    #    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    volumes:
      - auth-db-data:/var/lib/mysql
    networks:
      - app-network

  notifications:
    build:
      context: ./backend/notifications-service
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    env_file:
      - ./backend/notifications-service/.env.dev
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /notifications
    volumes:
      - ./backend/notifications-service:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  recipes:
    build:
      context: ./backend/recipes-service
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    env_file:
      - ./backend/recipes-service/.env.dev
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /recipes
    volumes:
      - ./backend/recipes-service:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      recipes-db:
        condition: service_started
    networks:
      - app-network

  recipes-db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: recipes_development
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: munchora
      MYSQL_PASSWORD: admin
    #      MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS: 1
    #    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    volumes:
      - recipes-db-data:/var/lib/mysql
    networks:
      - app-network

  shopping-lists:
    build:
      context: ./backend/shopping-lists-service
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    env_file:
      - ./backend/shopping-lists-service/.env.dev
    environment:
      RAILS_ENV: development
      RAILS_RELATIVE_URL_ROOT: /shopping-lists
    volumes:
      - ./backend/shopping-lists-service:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      shopping-lists-db:
        condition: service_started
    networks:
      - app-network

  shopping-lists-db:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: shopping_lists_development
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: munchora
      MYSQL_PASSWORD: admin
    #      MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS: 1
    #    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    volumes:
      - shopping-lists-db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  ai-db-data:
  auth-db-data:
  shopping-lists-db-data:
  recipes-db-data:
  rabbitmq_data: # Stores RabbitMQ data
  rabbitmq_log: # Stores RabbitMQ logs


networks:
  app-network:
    driver: bridge