source 'https://rubygems.org'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 8.0.4'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5'

# Using sqlite3 for testing
gem 'sqlite3', '~> 2.9', group: :test

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem 'bcrypt', '~> 3.1.7'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem 'solid_cache', '~> 1.0'
gem 'solid_queue', '~> 1.2'
gem 'solid_cable', '~> 3.0.12'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.20.1', require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem 'kamal', '~> 2.10.1', require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem 'thruster', '~> 0.1.17', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem 'rack-cors', '~> 3.0.0'

# Pagination
gem 'kaminari', '~> 1.2.2'

# Jwt for auth
gem 'jwt', '~> 3.1.2'

# Google OAuth SSO
gem 'google-id-token', '~> 1.4.2'

# To enable dotenv files
gem 'dotenv-rails', '~> 3.1', groups: [:development, :test]

gem 'newrelic_rpm', '~> 10.2.0'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[ mri windows ], require: 'debug/prelude'

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem 'brakeman', '~> 7.1.2', require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem 'rubocop-rails-omakase', '~> 1.1.0', require: false

  # Test coverage tracking tool
  gem 'simplecov', '~> 0.22.0', require: false

  # Rspec for TDD
  gem 'rspec-rails', '~> 8.0.2'
  gem 'factory_bot_rails', '~> 6.5.1'
  gem 'faker', '~> 3.5.2'
  gem 'webmock', '~> 3.26.1'
  gem 'shoulda-matchers', '~> 5.0'
end
